dataset:
  batch_size: 256
  input_steps: 48
  test: datasets/no1_validation.csv
  train: datasets/no1_train.csv
display_normed_vals: true
model:
  dropout: 0
  epochs: 20
  file_path: models/model_01
  force_retrain: false
  hidden_layers:
  - - lstm
    - 64
    - tanh
  learning_rate: 0.001
  reg_rate: 0.01
  regularization: l2
  visualize: true
  weight_file: models/model_01
num_visualizations: 10
preprocessing:
  avoid_structural_imbalance: false
  clamp_values: true
  imb_prev_day: false
  mean_imbalance: false
  normalize: true
  prev_imbalance: true
  subsample: false
  subsampling_rate: 1
  time_of_day: false
  time_of_week: false
  time_of_year: false
store_config: model_configs/model_01
