dataset:
  batch_size: 256
  input_steps: 144
  test: datasets/no1_validation.csv
  train: datasets/no1_train.csv
display_normed_vals: true
model:
  dropout: 0
  epochs: 20
  file_path: models/model_06
  force_retrain: false
  hidden_layers:
  - - lstm
    - 64
    - tanh
  learning_rate: 0.001
  reg_rate: 0.01
  regularization: l2
  visualize: true
  weight_file: models/model_06
num_visualizations: 10
preprocessing:
  avoid_structural_imbalance: false
  clamp_values: true
  features:
  - thermal
  - sys_reg
  - flow
  - time_of_year_sin
  - time_of_year_cos
  - previous_y
  - imb_prev_day
  - mean_imbalance
  imb_prev_day: true
  mean_imbalance: true
  normalize: true
  prev_imbalance: true
  subsample: false
  subsampling_rate: 1
  time_of_day: true
  time_of_week: true
  time_of_year: true
store_config: model_configs/model_06
