dataset:
  train: "datasets/no1_train.csv"
  test: "datasets/no1_validation.csv"
  input_steps: 72
  batch_size: 32
model:
  visualize: false
  learning_rate: 0.001
  force_retrain: false
  epochs: 20
  dropout: 0
  regularization: "l2"
  reg_rate: 0.01
  weight_file: "models/test"
  file_path: "models/test"
preprocessing:
  subsample: false
  subsampling_rate: 1
  clamp_values: true
  time_of_day: true
  time_of_week: true
  time_of_year: true
  prev_imbalance: true
  imb_prev_day: true
  mean_imbalance: true
  normalize: true