num_visualizations: 10
display_normed_vals: true
dataset:
  train: "datasets/no1_train.csv"
  test: "datasets/no1_validation.csv"
  input_steps: 48
  batch_size: 256
model:
  visualize: true
  learning_rate: 0.001
  force_retrain: false
  epochs: 20
  dropout: 0
  regularization: "l2"
  reg_rate: 0.1
  weight_file: "models/model_18lstm_48t"
  file_path: "models/model_18lstm_48t"
preprocessing:
  subsample: false
  subsampling_rate: 1
  clamp_values: true
  avoid_structural_imbalance: false
  time_of_day: true
  time_of_week: false
  time_of_year: false
  prev_imbalance: true
  imb_prev_day: false
  mean_imbalance: false
  normalize: true