num_visualizations: 10
display_normed_vals: true
store_config: "model_configs/model_01"
dataset:
  train: "datasets/no1_train.csv"
  test: "datasets/no1_validation.csv"
  input_steps: 144
  batch_size: 32
model:
  visualize: true
  learning_rate: 0.0001
  force_retrain: false
  epochs: 50
  dropout: 0
  #regularization: "l2"
  #reg_rate: 0.01
  hidden_layers: [
    ["lstm", 64, "tanh"]
  ]
  weight_file: "models/model_03"
  file_path: "models/model_03"
preprocessing:
  subsample: false
  subsampling_rate: 1
  clamp_values: true
  avoid_structural_imbalance: true
  time_of_day: true
  time_of_week: true
  time_of_year: true
  prev_imbalance: true
  imb_prev_day: true
  mean_imbalance: true
  normalize: true